Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/11/2020
Var
// Seção de Declarações das variáveis 
n1, n2, n3: inteiro
soma: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia (n1)
leia (n2)
leia (n3)
soma<-n1+n2+n3
escreva("O resultado é:", soma)

Fimalgoritmo